In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

from data import Processor
from network import Network

IMAGE_SIZE = (256, 256)

# Data preprocessing
p = Processor(train_path="train", test_path="test1")
X_train, y_train, X_test, y_test = p.import_data()

# Establishing the model
n = Network()
model = n.generate_model()

# Training the model
y_train_hot = p.one_hot_class(y_train)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics="accuracy")
model.fit(X_train, y_train_hot, epochs=50)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [19]:
y_pred = np.argmax(model.predict(X_test), axis=1)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))








[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]
1.0
