In [18]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

from data import Processor
from network import Network

IMAGE_SIZE = (256, 256)

# Data preprocessing
p = Processor(train_path="toy_train", test_path="toy_test1")
X_train, y_train, X_test, y_test = p.import_data()
print(X_train)

# Establishing the model
n = Network()
model = n.generate_model()

# Training the model
y_train_hot = p.one_hot_class(y_train)
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics="accuracy")
model.fit(X_train, y_train_hot, epochs=20)

[[[[0.1888174  0.13391544 0.12215074]
   [0.1888174  0.13391544 0.12215074]
   [0.18834252 0.13344056 0.12167586]
   ...
   [0.14752149 0.08071385 0.05285848]
   [0.14195832 0.07942768 0.0519767 ]
   [0.13863849 0.07843628 0.0509853 ]]

  [[0.19041054 0.13550858 0.12374387]
   [0.19041054 0.13550858 0.12374387]
   [0.18993566 0.1350337  0.123269  ]
   ...
   [0.14472106 0.07752757 0.04986512]
   [0.13961218 0.07708154 0.04963056]
   [0.1367653  0.0765631  0.04911212]]

  [[0.1940012  0.13909924 0.12733453]
   [0.19370105 0.13879909 0.12703439]
   [0.19269301 0.13779105 0.12602635]
   ...
   [0.14391827 0.07617941 0.04872843]
   [0.14012882 0.07653186 0.04908088]
   [0.13840069 0.07653186 0.04908088]]

  ...

  [[0.16310664 0.11212625 0.07683213]
   [0.16573522 0.11475483 0.07946071]
   [0.16969952 0.11871912 0.08342501]
   ...
   [0.10837917 0.15638775 0.06179522]
   [0.11712024 0.16004304 0.06592539]
   [0.1223774  0.16297177 0.06885412]]

  [[0.17668445 0.12570406 0.09040994]
   [0.1

In [19]:
y_pred = np.argmax(model.predict(X_test), axis=1)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))








[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]
[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]
1.0
